classdef MyoPose < ros.Message
    %MyoPose MATLAB implementation of ros_myo/MyoPose
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2021 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ros_myo/MyoPose' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '056fd823a1b40e3fef451ecc8dcf5690' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        REST = uint8(1)
        FIST = uint8(2)
        WAVEIN = uint8(3)
        WAVEOUT = uint8(4)
        FINGERSSPREAD = uint8(5)
        THUMBTOPINKY = uint8(6)
        UNKNOWN = uint8(0)
    end
    
    properties (Dependent)
        Pose
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Pose'} % List of non-constant message properties
        ROSPropertyList = {'pose'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MyoPose(msg)
            %MyoPose Construct the message object MyoPose
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function pose = get.Pose(obj)
            %get.Pose Get the value for property Pose
            pose = typecast(int8(obj.JavaMessage.getPose), 'uint8');
        end
        
        function set.Pose(obj, pose)
            %set.Pose Set the value for property Pose
            validateattributes(pose, {'numeric'}, {'nonempty', 'scalar'}, 'MyoPose', 'Pose');
            
            obj.JavaMessage.setPose(pose);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Pose = obj.Pose;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Pose = strObj.Pose;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Pose = obj.Pose;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.ros_myo.MyoPose.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.ros_myo.MyoPose;
            obj.reload(strObj);
        end
    end
end
